name: Test AWS OIDC config

on:
  push:
    branches: [ main, develop ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: agentic-ai
  ECS_CLUSTER: my-ecs-cluster
  ECS_SERVICE: my-ecs-service
  ECS_TASK_DEFINITION: infrastructure/task-definition.json

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Context
        run: |
            echo "Repository=${{ github.repository }}"
            echo "Ref=${{ github.ref }}"
            echo "Branch=${{ github.ref_name }}"
            echo "Event=${{ github.event_name }}"
            echo "Actor=${{ github.actor }}"

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Verify Identity
        run: aws sts get-caller-identity

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v250
         
      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
              -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
              -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest \
              .
      
      - name: Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest
