name: Test AWS OIDC config

on:
  push:
    branches: [ main, develop ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: viru/agentic-ai
  ECS_CLUSTER: default
  ECS_SERVICE: agentic-ai-4e7d
  ECS_TASK_DEFINITION: infrastructure/task-definition.json

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Context
        run: |
            echo "Repository=${{ github.repository }}"
            echo "Ref=${{ github.ref }}"
            echo "Branch=${{ github.ref_name }}"
            echo "Event=${{ github.event_name }}"
            echo "Actor=${{ github.actor }}"

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Verify Identity
        run: aws sts get-caller-identity

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
         
      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker buildx build \
              --platform linux/arm64 \
              --load \
              -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
              -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest \
              .
      
      - name: Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest

      - name: Render ECS Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: Main
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          
      - name: Deploy ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true